---
title: "LinearRegression"
author: "Temitope Folorunso"
date: "2025-04-01"
output: 
  pdf_document:
    toc: true 
  md_document:
    variant: gfm
---

# Linear Models

```{r setup, include=FALSE}
#install all packages needed
library(tidyverse)
library(lme4)
#install.packages("multcomp", ask = FALSE, dependencies = TRUE)
library(emmeans)
library(multcomp)
```
## Introduction to Regression Analysis in R

```{r include=TRUE}
data("mtcars")

ggplot(mtcars, aes(x = wt, y = mpg)) +
  geom_smooth(method = lm, se = FALSE, color = "grey") +
  geom_point(aes(color = wt)) +
  xlab("Weight") + 
  ylab("Miles per gallon") +
  scale_colour_gradient(low = "forestgreen", high = "black") +
  theme_classic()


lm1 <- lm(mpg~wt, data = mtcars)
summary(lm1)
anova(lm1)
cor.test(mtcars$wt, mtcars$mpg)
```
### Assumption
```{r}
model <- lm(mpg~wt, data = mtcars)

ggplot(model, aes(y = .resid, x = .fitted)) +
  geom_point() +
  geom_hline(yintercept = 0)
```
### Categorical Variable
```{r}
bull.rich <- read.csv("Data_Folder/Bull_richness.csv")
bull.rich %>%
  filter(GrowthStage == "V8" & Treatment == "Conv.") %>%
  ggplot(aes(x = Fungicide, y = richness)) + 
  geom_boxplot()

bull.rich.subset <- bull.rich %>%
  filter(GrowthStage == "V8" & Treatment == "Conv.") 

t.test(richness~ Fungicide, data =bull.rich.subset, var.equal = TRUE)
summary(lm(richness~Fungicide, data =bull.rich.subset))

anova(lm(richness~Fungicide, data = bull.rich.subset))
```
### ANOVA
```{r}
bull.rich.sub2 <- bull.rich %>%
  filter(Fungicide == "C" & Treatment == "Conv." & Crop == "Corn")
bull.rich.sub2$GrowthStage <- factor(bull.rich.sub2$GrowthStage, levels = c("V6", "V8", "V15"))

ggplot(bull.rich.sub2, aes(x = GrowthStage, y = richness)) +
  geom_boxplot()

lm.growth <- lm(richness ~ GrowthStage, data = bull.rich.sub2)
summary(lm.growth)

lmmeans <- emmeans(lm.growth,~GrowthStage)
lmmeans

results_lmeeans <- cld(lmmeans, alpha = 0.05, details = TRUE)
results_lmeeans
anova(lm.growth)

summary(aov(richness ~ GrowthStage, data = bull.rich.sub2))

bull.rich.subset3 <- bull.rich %>%
  filter(Treatment == "Conv." & Crop == "Corn")

lm.inter <- lm(richness ~ GrowthStage + Fungicide + GrowthStage:Fungicide, data = bull.rich.subset3)

# or like this
lm(richness ~ GrowthStage*Fungicide, data = bull.rich.subset3)
```
### Interactions
```{r}
bull.rich.subset3 <- bull.rich %>%
  filter(Treatment == "Conv." & Crop == "Corn")

lm.inter <- lm(richness ~ GrowthStage + Fungicide + GrowthStage:Fungicide, data = bull.rich.subset3)

# or like this
lm(richness ~ GrowthStage*Fungicide, data = bull.rich.subset3)
summary(lm.inter) # significant terms
anova(lm.inter) # The interaction term is signifant. 
lsmeans <- emmeans(lm.inter, ~Fungicide|GrowthStage) # estimate lsmeans of variety within siteXyear
Results_lsmeans <- cld(lsmeans, alpha = 0.05, reversed = TRUE, details = TRUE) # contrast with Tukey ajustment
Results_lsmeans

bull.rich.subset3 %>%
  ggplot(aes(x = GrowthStage, y = richness, color = Fungicide)) +
  geom_boxplot()
```
### Mixed effects models
```{r}

lme0 <- lm(richness ~ GrowthStage*Fungicide, data = bull.rich.subset3)
lme1 <- lmer(richness ~ GrowthStage*Fungicide + (1|Rep), data = bull.rich.subset3)
summary(lme1)
summary(lme0)
```

